# Generated by Django 4.2.16 on 2024-11-17 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notas', '0001_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='usser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sobre', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
