# Generated by Django 4.2.16 on 2024-12-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('numero3', models.IntegerField()),
                ('numero4', models.IntegerField()),
                ('numero5', models.IntegerField()),
            ],
        ),
    ]
